In [15]:
import pandas as pd
from lxml import etree
import xml.etree.ElementTree as ET
from pathlib import Path
import json

In [16]:
def read_year(identifier):
    pathlist = Path('../corpus').rglob(f'{identifier}_meta.json')
    for path in pathlist:
        with path.open('r', encoding='utf-8') as f:

                raw_metadata = json.load(f)

                return raw_metadata['year']

In [17]:
#TODO add remaining columns in the csv file
pathlist = Path('../corpus/').rglob('content.xhtml')
txt_rows=[]
csv_rows=[]
article_index=0

for path in pathlist:
    edition_id=path.parent.parent.stem
    tree = ET.ElementTree(etree.parse(path))
    year = read_year(edition_id)

    for div_article in tree.iterfind(".//{http://www.w3.org/1999/xhtml}div[@type='article']"):
        article_content = ""
        for note in div_article.iterfind(".//{http://www.w3.org/1999/xhtml}note"):
            article_content += note.text.strip() + " "
        
        article_name=edition_id+str(article_index)
        txt_row=[str(article_index),'0',article_content]
        csv_row=[article_name,str(article_index),str(year)]
        txt_rows.append(txt_row)
        csv_rows.append(csv_row)
        article_index+=1

In [18]:
with open('input.txt', 'w') as f:
    for row in txt_rows:
        f.write('\t'.join(row))
        f.write('\n')

In [20]:
df = pd.DataFrame(csv_rows, columns=["article_name", "article_index", "year"])
df.to_csv('documents.csv',index=False)

        article_name article_index  year
0      dark-37087460             0  1905
1      dark-37087461             1  1905
2      dark-37085812             2  1905
3      dark-37085813             3  1905
4      dark-37085814             4  1905
..               ...           ...   ...
345  dark-3708995345           345  1905
346  dark-3708487346           346  1905
347  dark-3708487347           347  1905
348  dark-3708487348           348  1905
349  dark-3708487349           349  1905

[350 rows x 3 columns]